#!/bin/bash
curl -fsSL https://get.docker.com | bash -s docker --mirror Aliyun
systemctl start docker
wget https://raw.githubusercontent.com/gd0772/zq/main/public.zip\napt install unzip -y && rm -rf /public && unzip -d / public.zip\ndocker volume create portainer_data && docker run -d -p 9000:9000 -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data -v /public:/public portainer/portainer:latest
